apiVersion: v1
kind: Service
metadata:
  name: db-service #nombre del servicio
  namespace: db-frida #nombre del namespace
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
