apiVersion: v1
kind: Service
metadata:
  name: mysql-container
  namespace: api-frida
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: NodePort
